name: Release and Upload

on:
  push:
    # tags:
    #   - 'v*'
    branches:
      - add-github-actions

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  DEPLOYMENT_NAME: cnv-email-plugin
  IMAGE: cnv-email-plugin
  REGISTRY: europe-west3-docker.pkg.dev
  NAMESPACE: cnv-email-plugin

jobs:
  build-release:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |-
          yarn
          yarn build

      - name: Test
        run: yarn test

      - name: Pack
        run: yarn pack

      - name: Create Tag
        id: create-tag
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # dry_run: true
          release_branches: add-github-actions

      # - name: Output tag action
      #   run: |-
      #     echo ${{ steps.create-tag.outputs.new_tag }}
      #     echo ${{ steps.create-tag.outputs.new_version }}
      #     echo ${{ steps.create-tag.outputs.previous-_tag }}
      #     echo ${{ steps.create-tag.outputs.changelog }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*.tgz'
          commit: add-github-actions
          tag: ${{ steps.create-tag.outputs.new_tag }}
          generateReleaseNotes: true

      - name: Update package.json version
        run: |-
          git config --global user.email "tinybuilder@productdock.com"
          git config --global user.name "TinyBuilder"
          npm version ${{ steps.create-tag.outputs.new_version }}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ steps.create-tag.outputs.new_version }}
          release-notes: ${{ steps.create-tag.outputs.changelog }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: add-github-actions
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
